config/axiom.toml
config/order.toml
go.mod
go.sum
internal/coreapi/api/api.go
internal/coreapi/broker.go
internal/order/rbft/adaptor/adaptor.go
internal/order/rbft/adaptor/adaptor_test.go
internal/order/rbft/config.go
internal/order/rbft/node.go
internal/order/rbft/node_test.go
internal/order/rbft/testutil/test_util.go
internal/order/rbft/tx_cache.go
internal/peermgr/handle.go
internal/peermgr/swarm.go
pkg/repo/order.go

feat: support p2p limit switch
fix: rbft adaptor checkpoint epoch bug

feat: adapt mempool in rbft

---

Makefile
api/jsonrpc/namespaces/eth/filters/api.go
cmd/axiom/main.go
cmd/axiom/start.go
config/axiom.toml
internal/app/axiom.go
internal/app/feedhub.go
internal/executor/executor_dev/executor_dev.go
internal/executor/executor_test.go
internal/order/rbft/node.go
internal/order/solo/node.go
internal/order/solo_dev/node_dev.go
internal/order/txcache/tx_cache.go
pkg/repo/config.go
pkg/repo/constant.go
scripts/cluster.sh
scripts/solo.sh

test: add executor dev mode
modify limit

test: add solo dev mode

---

go.mod
go.sum

1.fix the history of viewchange msgs failed to clean up 2.fix epoch Info failed to update

fix(order): fix abnormal viewchange

---

go.mod
go.sum
internal/order/precheck/precheckmgr.go
internal/order/precheck/precheckmgr_test.go
pkg/repo/order.go

feat: add consensus metrics

---

Makefile
api/jsonrpc/namespaces/eth/blockchain_api.go
api/jsonrpc/namespaces/eth/common.go
api/jsonrpc/namespaces/net/api.go
internal/app/axiom_ledger.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/ledger/ledger.go
internal/ledger/ledger_impl.go
internal/ledger/ledger_impl_test.go
internal/ledger/mock_ledger/mock_ledger.go
internal/ledger/state_ledger.go
internal/peermgr/gater.go
internal/peermgr/handle_test.go
pkg/repo/config.go

1. No more queries for journal info
2. Use the same accountCache as the rw ledger

feat(ledger): optimize the performance of view ledger

---

api/jsonrpc/namespaces/eth/filters/api.go
cmd/axiom-ledger/config.go
cmd/axiom-ledger/ledger.go
cmd/axiom-ledger/start.go
go.mod
go.sum
internal/executor/handle.go
internal/ledger/account.go
internal/ledger/evmstate_accessor.go
internal/ledger/inner_account.go
internal/ledger/ledger.go
internal/ledger/mock_ledger/mock_ledger.go
internal/ledger/state_accessor.go
pkg/loggers/loggers.go
pkg/repo/chainnet.go
pkg/repo/config.go

1. simple sync to target height (by replaying transactions)
2. add ledger debug log
3. support for replaying a block to compare ledger execution logic consistency

feat(cmd): add ledger simple sync cmd tool

---

api/jsonrpc/namespaces/eth/transaction_api.go
internal/executor/system/access/kyc_verification.go
internal/executor/system/access/kyc_verification_test.go
internal/executor/system/common/common.go
internal/executor/system/governance/council_manager.go
internal/executor/system/governance/council_manager_test.go
internal/executor/system/governance/kycservice_manager.go
internal/executor/system/governance/kycservice_manager_test.go
internal/executor/system/governance/node_manager.go
internal/executor/system/governance/node_manager_test.go
internal/ledger/account.go

fix: add gas for kyc service

---

api/jsonrpc/namespaces/eth/transaction_api.go
internal/executor/system/access/kyc_verification.go
internal/executor/system/access/kyc_verification_test.go
internal/executor/system/common/common.go
internal/executor/system/governance/council_manager.go
internal/executor/system/governance/council_manager_test.go
internal/executor/system/governance/kycservice_manager.go
internal/executor/system/governance/kycservice_manager_test.go
internal/executor/system/governance/node_manager.go
internal/executor/system/governance/node_manager_test.go
internal/ledger/account.go

Reverts axiomesh/axiom-ledger#170

Revert "fix: add gas for kyc service"

---

api/jsonrpc/namespaces/eth/transaction_api.go
go.mod
go.sum
internal/consensus/precheck/mock_precheck/mock_precheck.go
internal/consensus/rbft/adaptor/adaptor.go
internal/consensus/rbft/adaptor/epoch_service.go
internal/consensus/rbft/adaptor/network.go
internal/consensus/rbft/adaptor/storage.go
internal/consensus/rbft/adaptor/storage_test.go
internal/consensus/rbft/node.go
internal/consensus/rbft/node_test.go
internal/coreapi/api/mock_api/mock_api.go
internal/executor/executor_test.go
internal/executor/system/access/kyc_verification.go
internal/executor/system/access/kyc_verification_test.go
internal/executor/system/contract.go
internal/executor/system/governance/kycservice_manager.go
internal/executor/system/governance/kycservice_manager_test.go
internal/executor/system/governance/proposal_test.go
internal/ledger/mock_ledger/mock_ledger.go
internal/network/mock_network/mock_network.go
internal/storagemgr/storage_mgr.go
pkg/repo/config.go

1.fix unable to block properly after the storage is deleted and restart 2.epoch-proof is stored separately
3.use vtproto instead of gogoproto
4.generate full NewView after checkpoint when wrf

fix: fix bft bugs

---

internal/block_sync/block_sync_test.go
internal/consensus/precheck/precheckmgr_test.go
internal/consensus/txcache/tx_cache_test.go
pkg/repo/chainnet.go
pkg/repo/config.go

feat: decrease wait timeout when block sync

fix: multi unit test case concurrent problem

---

api/jsonrpc/namespaces/eth/axiom_api.go
go.mod
go.sum
internal/consensus/precheck/precheckmgr.go
pkg/repo/chainnet.go
pkg/repo/config.go
pkg/repo/constant.go

fix: precheck balance with gasprice from chainmeta

fix: remove gasprice rate

---

go.mod
go.sum
internal/consensus/precheck/metrics.go
internal/consensus/precheck/precheck_util_test.go
internal/consensus/precheck/precheckmgr.go
internal/consensus/precheck/precheckmgr_test.go
internal/executor/executor_test.go

feat: add metrics for precheck

feat: verify parallel for sign and balance

---

.github/workflows/release.yml
Makefile

cd for tag release , for example:
axiom_ledger_darwin_x86_64_v0.0.2.tar.gz
axiom_ledger_linux_amd64_v0.0.2.tar.gz

feat: cd for package release

---

go.mod
go.sum
internal/txpool/txpoolImpl.go
internal/txpool/txpool_test.go
internal/txpool/types.go

feat: implement adding rebroadcast txs

feat: remove ready txs when it‘s nonce smaller than committed nonce

---

api/jsonrpc/namespaces/eth/axiom_api.go
internal/executor/executor_test.go
internal/executor/system/governance/council_manager.go
internal/executor/system/governance/council_manager_test.go
internal/executor/system/governance/gas_manager_test.go
internal/executor/system/governance/governance_test.go
internal/executor/system/governance/node_manager_test.go
internal/executor/system/governance/white_list_provider_manager_test.go
internal/executor/system/native_vm.go
internal/executor/system/native_vm_test.go
internal/executor/system/sol/AxmManager.abi
internal/executor/system/token/axm_manager.go
internal/executor/system/token/types.go
pkg/repo/chainnet.go
pkg/repo/genesis.go

feat: Forbidden external call mint/burn method in token contract

refactor: support init every account balance in genesis config

---

api/jsonrpc/namespaces/axm/tx_pool_api.go
go.mod
go.sum
internal/app/axiom_ledger.go
internal/app/feedhub.go
internal/components/utils.go
internal/consensus/common/config.go
internal/consensus/precheck/precheck_util_test.go
internal/consensus/precheck/precheckmgr.go
internal/consensus/precheck/precheckmgr_test.go
internal/consensus/solo/node_test.go
internal/consensus/solo/node_util_test.go
internal/coreapi/api/api.go
internal/coreapi/tx_pool.go
internal/txpool/config.go
internal/txpool/txpoolImpl.go
internal/txpool/txpoolImpl_pooi_Info.go
internal/txpool/txpool_test.go
internal/txpool/types.go
internal/txpool/util_test.go

feat: Generate batch need validate tx data:
1. ensure txGasPrice > chainGasPrice;
2. ensure account have sufficient Balance.
feat: if validate tx data failed, trigger to remove invalid tx from txpool

feat: support update chainInfo when persisted new block

---

api/jsonrpc/txpool/tx_pool_api.go
api/jsonrpc/txpool/types.go
internal/app/axiom_ledger.go
internal/components/timer/timer.go
internal/consensus/rbft/node.go
internal/consensus/solo/node.go
internal/consensus/txcache/tx_cache.go
internal/txpool/btree_index.go
internal/txpool/config.go
internal/txpool/handle_test.go
internal/txpool/heap.go
internal/txpool/helper.go
internal/txpool/metrics.go
internal/txpool/priority_queue.go
internal/txpool/priority_queue_test.go
internal/txpool/tx_records.go
internal/txpool/tx_records_test.go
internal/txpool/tx_store.go
internal/txpool/txpoolImpl.go
internal/txpool/txpoolImpl_pooi_Info.go
internal/txpool/txpoolImpl_test.go
internal/txpool/types.go
internal/txpool/util_test.go
pkg/repo/chainnet.go
pkg/repo/consensus.go
pkg/repo/constant.go

feat: support replace tx with high gasPrice
fix: tx record not rebroadcast txs when it starts

feat: support gas priority mode

---

api/jsonrpc/txpool/tx_pool_api.go
api/jsonrpc/txpool/types.go
go.mod
go.sum
internal/consensus/precheck/metrics.go
internal/consensus/precheck/mock_precheck/mock_min_precheck.go
internal/consensus/precheck/mock_precheck/mock_precheck.go
internal/consensus/precheck/precheck.go
internal/consensus/precheck/precheckmgr.go
internal/consensus/precheck/precheckmgr_test.go
internal/consensus/precheck/types.go
internal/consensus/rbft/adaptor/adaptor_test.go
internal/consensus/rbft/node.go
internal/consensus/rbft/node_test.go
internal/consensus/rbft/testutil/test_util.go
internal/consensus/solo/node.go
internal/consensus/solo/node_test.go
internal/consensus/solo/node_util_test.go
internal/coreapi/api/api.go
internal/coreapi/tx_pool.go
internal/txpool/tx_records_test.go
internal/txpool/tx_store.go
internal/txpool/txpoolImpl.go
internal/txpool/txpoolImpl_pooi_Info.go
internal/txpool/txpoolImpl_test.go

feat: add txpool started flag for txpool rpc
refactor: mock txpool for consensus
fix: txpool counter

fix: get status from rbft

---

cmd/axiom-ledger/ledger.go
internal/storagemgr/cache_wrapper_test.go

fix: import-accounts by config

fix: import-accounts by config

---

go.mod
go.sum
internal/executor/handle.go
internal/sync/full_sync/full_sync.go
internal/txpool/heap.go
internal/txpool/priority_queue.go
internal/txpool/txpoolImpl.go
internal/txpool/txpoolImpl_test.go

fix: removeTxBeforeNonce in priority_queue

fix: reply batch signal

---

api/jsonrpc/namespaces/eth/filters/filter.go

fix: fix getLogs may

---

internal/consensus/rbft/data_syncer/heap.go
internal/consensus/rbft/data_syncer/node.go
internal/consensus/rbft/node.go

fix: restart sync state when state response can not reach quorum

---

cmd/axiom-ledger/cluster.go
cmd/axiom-ledger/cluster_helper.go
internal/executor/system/framework/staking_manager_test.go
pkg/repo/consensus.go
pkg/repo/constant.go
pkg/repo/genesis.go

fix the bug caused by multiple references to a pointer-type defaultValue

fix: the configuration issue

---

cmd/axiom-ledger/ledger.go
internal/app/axiom_ledger.go
internal/app/snap_sync.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/sync/sync_manager.go
internal/txpool/txpoolImpl.go

feat: dismiss snap meta of epoch and peers

fix: ignore execute repeat block

---

api/jsonrpc/txpool/tx_pool_api.go
api/jsonrpc/txpool/types.go
internal/consensus/common/types.go
internal/consensus/rbft/data_syncer/handle.go
internal/consensus/rbft/data_syncer/node.go
internal/consensus/rbft/data_syncer/node_test.go
internal/consensus/rbft/data_syncer/types.go
internal/consensus/rbft/data_syncer/util_test.go
internal/txpool/txpoolImpl.go

feat: sort tx set with nonce in txpool son-rpc

feat: support rebroadcast ready txs with data syncer
